server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    listener:
      simple:
        retry:
          initial-interval: 3s
          enabled: true
          max-attempts: 5
          max-interval: 5s
          multiplier: 1
        missing-queues-fatal: false

rabbitmq:
  queue:
    notification: NOTIFICATION_Q
    notification-dlq: NOTIFICATION_DLQ
    mail: MAIL_Q
    telegram: TELEGRAM_Q